"""迁移脚本

Revision ID: 618a9536f363
Revises: b59696a3f797
Create Date: 2026-03-25 09:21:51.625268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '618a9536f363'
down_revision: Union[str, None] = 'b59696a3f797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modbus_agent_sessions',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('session_id', sa.String(length=50), nullable=False, comment='会话ID'),
    sa.Column('last_device_id', sa.Integer(), nullable=True, comment='最后操作设备ID'),
    sa.Column('last_tag_id', sa.Integer(), nullable=True, comment='最后操作点位ID'),
    sa.Column('operation_context', sa.JSON(), nullable=True, comment='操作上下文'),
    sa.Column('chat_history', sa.JSON(), nullable=True, comment='对话历史'),
    sa.Column('last_active', sa.DateTime(), nullable=True, comment='最后活跃时间'),
    sa.Column('ttl_minutes', sa.Integer(), nullable=False, comment='会话TTL(分钟)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='是否启用(0:启用 1:禁用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注/描述'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Agent 会话表'
    )
    op.create_index(op.f('ix_modbus_agent_sessions_created_time'), 'modbus_agent_sessions', ['created_time'], unique=False)
    op.create_index(op.f('ix_modbus_agent_sessions_id'), 'modbus_agent_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_modbus_agent_sessions_session_id'), 'modbus_agent_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_modbus_agent_sessions_status'), 'modbus_agent_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_modbus_agent_sessions_updated_time'), 'modbus_agent_sessions', ['updated_time'], unique=False)
    op.create_index(op.f('ix_modbus_agent_sessions_user_id'), 'modbus_agent_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_modbus_agent_sessions_uuid'), 'modbus_agent_sessions', ['uuid'], unique=True)
    op.create_table('modbus_chat_history',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('session_id', sa.String(length=50), nullable=False, comment='会话ID'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='首条用户消息摘要'),
    sa.Column('messages', sa.JSON(), nullable=False, comment='消息列表'),
    sa.Column('device_count', sa.Integer(), nullable=False, comment='涉及设备数'),
    sa.Column('device_names', sa.JSON(), nullable=True, comment='设备名称列表'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='是否启用(0:启用 1:禁用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注/描述'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='聊天历史表'
    )
    op.create_index(op.f('ix_modbus_chat_history_created_time'), 'modbus_chat_history', ['created_time'], unique=False)
    op.create_index(op.f('ix_modbus_chat_history_id'), 'modbus_chat_history', ['id'], unique=False)
    op.create_index(op.f('ix_modbus_chat_history_session_id'), 'modbus_chat_history', ['session_id'], unique=True)
    op.create_index(op.f('ix_modbus_chat_history_status'), 'modbus_chat_history', ['status'], unique=False)
    op.create_index(op.f('ix_modbus_chat_history_updated_time'), 'modbus_chat_history', ['updated_time'], unique=False)
    op.create_index(op.f('ix_modbus_chat_history_user_id'), 'modbus_chat_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_modbus_chat_history_uuid'), 'modbus_chat_history', ['uuid'], unique=True)
    op.create_table('modbus_devices',
    sa.Column('name', sa.String(length=100), nullable=False, comment='设备名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='设备编码'),
    sa.Column('group_name', sa.String(length=50), nullable=True, comment='分组名称'),
    sa.Column('connection_type', sa.String(length=20), nullable=False, comment='连接类型(TCP/RTU_OVER_TCP)'),
    sa.Column('host', sa.String(length=100), nullable=False, comment='IP地址'),
    sa.Column('port', sa.Integer(), nullable=False, comment='端口'),
    sa.Column('slave_id', sa.Integer(), nullable=False, comment='从站ID'),
    sa.Column('baud_rate', sa.Integer(), nullable=True, comment='波特率'),
    sa.Column('parity', sa.String(length=10), nullable=True, comment='校验位'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('device_status', sa.String(length=20), nullable=False, comment='设备状态(online/offline/error)'),
    sa.Column('last_seen', sa.DateTime(), nullable=True, comment='最后在线时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='是否启用(0:启用 1:禁用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注/描述'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='PLC 设备表'
    )
    op.create_index(op.f('ix_modbus_devices_created_time'), 'modbus_devices', ['created_time'], unique=False)
    op.create_index(op.f('ix_modbus_devices_id'), 'modbus_devices', ['id'], unique=False)
    op.create_index(op.f('ix_modbus_devices_status'), 'modbus_devices', ['status'], unique=False)
    op.create_index(op.f('ix_modbus_devices_updated_time'), 'modbus_devices', ['updated_time'], unique=False)
    op.create_index(op.f('ix_modbus_devices_uuid'), 'modbus_devices', ['uuid'], unique=True)
    op.create_table('modbus_tags',
    sa.Column('device_id', sa.Integer(), nullable=False, comment='设备ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='点位名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='点位编码'),
    sa.Column('address', sa.Integer(), nullable=False, comment='寄存器地址'),
    sa.Column('register_type', sa.String(length=20), nullable=False, comment='寄存器类型(holding/input/coil/discrete)'),
    sa.Column('data_type', sa.String(length=20), nullable=False, comment='数据类型(INT16/UINT16/INT32/FLOAT/BOOL)'),
    sa.Column('byte_order', sa.String(length=10), nullable=False, comment='字节序'),
    sa.Column('access_type', sa.String(length=20), nullable=False, comment='访问类型(READ/WRITE/READ_WRITE)'),
    sa.Column('min_value', sa.Float(), nullable=False, comment='最小值'),
    sa.Column('max_value', sa.Float(), nullable=False, comment='最大值'),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='单位'),
    sa.Column('scale_factor', sa.Float(), nullable=False, comment='缩放因子'),
    sa.Column('offset', sa.Float(), nullable=False, comment='偏移量'),
    sa.Column('aliases', sa.JSON(), nullable=True, comment='语义别名列表'),
    sa.Column('requires_confirmation', sa.Boolean(), nullable=False, comment='是否需要确认'),
    sa.Column('confirmation_threshold', sa.Float(), nullable=True, comment='确认阈值比例'),
    sa.Column('current_value', sa.Float(), nullable=True, comment='当前值'),
    sa.Column('last_updated', sa.DateTime(), nullable=True, comment='最后更新时间'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='是否启用(0:启用 1:禁用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注/描述'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['device_id'], ['modbus_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='设备点位表'
    )
    op.create_index(op.f('ix_modbus_tags_created_time'), 'modbus_tags', ['created_time'], unique=False)
    op.create_index(op.f('ix_modbus_tags_device_id'), 'modbus_tags', ['device_id'], unique=False)
    op.create_index(op.f('ix_modbus_tags_id'), 'modbus_tags', ['id'], unique=False)
    op.create_index(op.f('ix_modbus_tags_status'), 'modbus_tags', ['status'], unique=False)
    op.create_index(op.f('ix_modbus_tags_updated_time'), 'modbus_tags', ['updated_time'], unique=False)
    op.create_index(op.f('ix_modbus_tags_uuid'), 'modbus_tags', ['uuid'], unique=True)
    op.create_table('modbus_command_logs',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='操作用户ID'),
    sa.Column('session_id', sa.String(length=50), nullable=True, comment='Agent 会话ID'),
    sa.Column('device_id', sa.Integer(), nullable=True, comment='设备ID'),
    sa.Column('tag_id', sa.Integer(), nullable=True, comment='点位ID'),
    sa.Column('action', sa.String(length=10), nullable=False, comment='操作类型(READ/WRITE)'),
    sa.Column('request_value', sa.Float(), nullable=True, comment='请求值'),
    sa.Column('actual_value', sa.Float(), nullable=True, comment='实际值'),
    sa.Column('log_status', sa.String(length=20), nullable=False, comment='状态(pending/success/failed/cancelled)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('confirmation_required', sa.Boolean(), nullable=False, comment='是否需要确认'),
    sa.Column('confirmed_by', sa.Integer(), nullable=True, comment='确认人ID'),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True, comment='确认时间'),
    sa.Column('ai_reasoning', sa.Text(), nullable=True, comment='AI 推理过程'),
    sa.Column('user_input', sa.Text(), nullable=True, comment='用户原始输入'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='重试次数'),
    sa.Column('execution_time', sa.Float(), nullable=True, comment='执行耗时(毫秒)'),
    sa.Column('executed_at', sa.DateTime(), nullable=True, comment='执行时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='是否启用(0:启用 1:禁用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注/描述'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['modbus_devices.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['modbus_tags.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='PLC 操作审计日志表'
    )
    op.create_index(op.f('ix_modbus_command_logs_created_time'), 'modbus_command_logs', ['created_time'], unique=False)
    op.create_index(op.f('ix_modbus_command_logs_id'), 'modbus_command_logs', ['id'], unique=False)
    op.create_index(op.f('ix_modbus_command_logs_status'), 'modbus_command_logs', ['status'], unique=False)
    op.create_index(op.f('ix_modbus_command_logs_updated_time'), 'modbus_command_logs', ['updated_time'], unique=False)
    op.create_index(op.f('ix_modbus_command_logs_user_id'), 'modbus_command_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_modbus_command_logs_uuid'), 'modbus_command_logs', ['uuid'], unique=True)
    op.create_table('modbus_pending_confirms',
    sa.Column('user_id', sa.Integer(), nullable=True, comment='创建者用户ID'),
    sa.Column('command_log_id', sa.Integer(), nullable=True, comment='关联命令日志ID'),
    sa.Column('device_name', sa.String(length=100), nullable=True, comment='设备名称'),
    sa.Column('tag_name', sa.String(length=100), nullable=True, comment='点位名称'),
    sa.Column('target_value', sa.Float(), nullable=True, comment='目标值'),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='单位'),
    sa.Column('confirm_status', sa.String(length=20), nullable=False, comment='状态(pending/confirmed/rejected/expired)'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='过期时间'),
    sa.Column('reviewed_by', sa.Integer(), nullable=True, comment='审核人ID'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('review_comment', sa.Text(), nullable=True, comment='审核备注'),
    sa.Column('user_input', sa.Text(), nullable=True, comment='用户输入'),
    sa.Column('ai_explanation', sa.Text(), nullable=True, comment='AI 解释'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='是否启用(0:启用 1:禁用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注/描述'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['command_log_id'], ['modbus_command_logs.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='待确认操作表'
    )
    op.create_index(op.f('ix_modbus_pending_confirms_created_time'), 'modbus_pending_confirms', ['created_time'], unique=False)
    op.create_index(op.f('ix_modbus_pending_confirms_id'), 'modbus_pending_confirms', ['id'], unique=False)
    op.create_index(op.f('ix_modbus_pending_confirms_status'), 'modbus_pending_confirms', ['status'], unique=False)
    op.create_index(op.f('ix_modbus_pending_confirms_updated_time'), 'modbus_pending_confirms', ['updated_time'], unique=False)
    op.create_index(op.f('ix_modbus_pending_confirms_uuid'), 'modbus_pending_confirms', ['uuid'], unique=True)
    # 注意：保留 apscheduler_jobs 表，不删除
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 注意：不恢复 apscheduler_jobs 表（它从未被删除）
    op.drop_index(op.f('ix_modbus_pending_confirms_uuid'), table_name='modbus_pending_confirms')
    op.drop_index(op.f('ix_modbus_pending_confirms_updated_time'), table_name='modbus_pending_confirms')
    op.drop_index(op.f('ix_modbus_pending_confirms_status'), table_name='modbus_pending_confirms')
    op.drop_index(op.f('ix_modbus_pending_confirms_id'), table_name='modbus_pending_confirms')
    op.drop_index(op.f('ix_modbus_pending_confirms_created_time'), table_name='modbus_pending_confirms')
    op.drop_table('modbus_pending_confirms')
    op.drop_index(op.f('ix_modbus_command_logs_uuid'), table_name='modbus_command_logs')
    op.drop_index(op.f('ix_modbus_command_logs_user_id'), table_name='modbus_command_logs')
    op.drop_index(op.f('ix_modbus_command_logs_updated_time'), table_name='modbus_command_logs')
    op.drop_index(op.f('ix_modbus_command_logs_status'), table_name='modbus_command_logs')
    op.drop_index(op.f('ix_modbus_command_logs_id'), table_name='modbus_command_logs')
    op.drop_index(op.f('ix_modbus_command_logs_created_time'), table_name='modbus_command_logs')
    op.drop_table('modbus_command_logs')
    op.drop_index(op.f('ix_modbus_tags_uuid'), table_name='modbus_tags')
    op.drop_index(op.f('ix_modbus_tags_updated_time'), table_name='modbus_tags')
    op.drop_index(op.f('ix_modbus_tags_status'), table_name='modbus_tags')
    op.drop_index(op.f('ix_modbus_tags_id'), table_name='modbus_tags')
    op.drop_index(op.f('ix_modbus_tags_device_id'), table_name='modbus_tags')
    op.drop_index(op.f('ix_modbus_tags_created_time'), table_name='modbus_tags')
    op.drop_table('modbus_tags')
    op.drop_index(op.f('ix_modbus_devices_uuid'), table_name='modbus_devices')
    op.drop_index(op.f('ix_modbus_devices_updated_time'), table_name='modbus_devices')
    op.drop_index(op.f('ix_modbus_devices_status'), table_name='modbus_devices')
    op.drop_index(op.f('ix_modbus_devices_id'), table_name='modbus_devices')
    op.drop_index(op.f('ix_modbus_devices_created_time'), table_name='modbus_devices')
    op.drop_table('modbus_devices')
    op.drop_index(op.f('ix_modbus_chat_history_uuid'), table_name='modbus_chat_history')
    op.drop_index(op.f('ix_modbus_chat_history_user_id'), table_name='modbus_chat_history')
    op.drop_index(op.f('ix_modbus_chat_history_updated_time'), table_name='modbus_chat_history')
    op.drop_index(op.f('ix_modbus_chat_history_status'), table_name='modbus_chat_history')
    op.drop_index(op.f('ix_modbus_chat_history_session_id'), table_name='modbus_chat_history')
    op.drop_index(op.f('ix_modbus_chat_history_id'), table_name='modbus_chat_history')
    op.drop_index(op.f('ix_modbus_chat_history_created_time'), table_name='modbus_chat_history')
    op.drop_table('modbus_chat_history')
    op.drop_index(op.f('ix_modbus_agent_sessions_uuid'), table_name='modbus_agent_sessions')
    op.drop_index(op.f('ix_modbus_agent_sessions_user_id'), table_name='modbus_agent_sessions')
    op.drop_index(op.f('ix_modbus_agent_sessions_updated_time'), table_name='modbus_agent_sessions')
    op.drop_index(op.f('ix_modbus_agent_sessions_status'), table_name='modbus_agent_sessions')
    op.drop_index(op.f('ix_modbus_agent_sessions_session_id'), table_name='modbus_agent_sessions')
    op.drop_index(op.f('ix_modbus_agent_sessions_id'), table_name='modbus_agent_sessions')
    op.drop_index(op.f('ix_modbus_agent_sessions_created_time'), table_name='modbus_agent_sessions')
    op.drop_table('modbus_agent_sessions')
    # ### end Alembic commands ###
